
printout = 0;

load('dHCP_edited_surf_data.mat')

clf

%N = 120;
N = 30;
r = linspace(0,1,N);
r2use = r(2:end);
SmallFont = 8;
LargeFont = 72;

fontsizing = linspace(SmallFont,LargeFont,N);
fontsizing = fontsizing(2:end-1);
fontsizing_ = fliplr(fontsizing);
fontspacing = round(linspace(0,10,N));
fontspacing = fontspacing(2:end-1);
fontspacing_ = fliplr(fontspacing);

Pos1 = linspace(.5,.25,N);
Pos1 = Pos1(2:end-1);
Pos2 = linspace(.75,.5,N);
Pos2 = Pos2(2:end-1);

F = length(r2use);

p = patch('Faces',faces,'Vertices',vertices_GA{1});
set(p,'FaceColor',[.5 .5 .5],'EdgeColor','none','FaceLighting','gouraud','Clipping','off')
axis off
axis tight
axis equal
%axis vis3d
material dull
view([-90 0])
clight = camlight('headlight');

p.Vertices = vertices_GA{end};

xlimits = xlim;
ylimits = ylim;
zlimits = zlim;

xlim(xlimits)
ylim(ylimits)
ylim(ylimits)

GAweek_naming = GA;
annotsize = .35;
Iter = 1;
i = 1;
p.Vertices = vertices_GA{i};
 A = annotation(gcf,'textbox',...
[0.25-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)-1),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',SmallFont,...
'FitBoxToText','off',...
'EdgeColor','none');

B = annotation(gcf,'textbox',...
[0.5-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',LargeFont,...
'FitBoxToText','off',...
'EdgeColor','none');

C = annotation(gcf,'textbox',...
[0.75-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)+1),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',SmallFont,...
'FitBoxToText','off',...
'EdgeColor','none');
if printout
 print(['./Imgs/Img',num2str(Iter),'.png'],'-dpng')
end
Iter = Iter + 1;
for i = 1:length(GA)-5
    for j = 1:F
newVerts = find_point_on_line(vertices_GA{i},vertices_GA{i+1},r2use(j));
p.Vertices = newVerts;
if exist('A','var')
delete(A)
end
if exist('B','var')
delete(B)
end
if exist('C','var')
delete(C)
end
if j == F
 A = annotation(gcf,'textbox',...
[0.25-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',SmallFont,...
'FitBoxToText','off',...
'EdgeColor','none');

B = annotation(gcf,'textbox',...
[0.5-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)+1),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',LargeFont,...
'FitBoxToText','off',...
'EdgeColor','none');

C = annotation(gcf,'textbox',...
[0.75-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)+2),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',SmallFont,...
'FitBoxToText','off',...
'EdgeColor','none');
else
B = annotation(gcf,'textbox',...
[Pos1(j)-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',fontsizing_(j),...
'FitBoxToText','off',...
'EdgeColor','none');

C = annotation(gcf,'textbox',...
[Pos2(j)-(annotsize/2),0.935,annotsize,0.05],...
'VerticalAlignment','middle',...
'String',[num2str(GAweek_naming(i)+1),' weeks'],...
'HorizontalAlignment','center',...
'FontSize',fontsizing(j),...
'FitBoxToText','off',...
'EdgeColor','none');    
end

pause(.1)
if printout
print(['./Imgs/Img',num2str(Iter),'.png'],'-dpng')
end
Iter = Iter + 1;
    end
end